name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: |
        sudo add-apt-repository ppa:gnuradio/gnuradio-releases
        sudo apt update
        sudo apt install gnuradio libprotobuf-dev protobuf-compiler swig doxygen graphviz
    - name: run-cmake
      uses: lukka/run-cmake@v2.5
      with:
        buildDirectory: '${{ runner.workspace }}/build'
    - name: run-cmake-tests
      uses: lukka/run-cmake@v2.5
      with:
        buildDirectory: '${{ runner.workspace }}/build'
        buildWithCMakeArgs: --target test
    - name: Store binaries
      uses: actions/upload-artifact@v2
      with:
        name: gr-meteor
        path: '${{ runner.workspace }}/build/lib/libgnuradio-meteor.so*'
